name: "pluginval"
description: "Downloads and runs pluginval against VST3"
runs:
  using: "composite"
  steps:
    - name: Download Pluginval
      shell: bash
      run: |
        curl -LO "https://github.com/Tracktion/pluginval/releases/download/v1.0.3/pluginval_${{ matrix.name }}.zip"
        7z x pluginval_${{ matrix.name }}.zip
    - name: Run Pluginval
      shell: bash
      run: ${{ matrix.pluginval-binary }} --strictness-level 10 --verbose --validate "${{ env.VST3_PATH }}"