name: "build_and_test_arm"
description: "Setup VCKPG, CMake, build, test and cache"
runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.5.1"
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
    - name: Run CMake consuming CMakePreset.json and run vcpkg to build dependencies
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'arm64-osx'
        configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
        buildPreset: 'build-arm64-osx-release'
        buildPresetAdditionalArgs: "['--parallel 4']"
        testPreset: 'test-arm64-osx-release'