//
// Created by Micah Strange on 05/04/2024.
//

#ifndef ZONES_MODULES_IR_FORMAT_SRC_IR_FORMAT_FORMATTER_MONOFORMATTER_H_
#define ZONES_MODULES_IR_FORMAT_SRC_IR_FORMAT_FORMATTER_MONOFORMATTER_H_

class MonoFormatter
{
};

#endif // ZONES_MODULES_IR_FORMAT_SRC_IR_FORMAT_FORMATTER_MONOFORMATTER_H_
