name: "build_ui"
description: "Setup Node and build UI"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install and Build UI
      working-directory: ./client/ui
      shell: bash
      run: npm ci && npm run build