name: "package_macos"
description: "Code-sign, apple notary service and package"
inputs:
  DEV_ID_APP_CERT:
    description: 'DEV_ID_APP_CERT'
    required: true
  DEV_ID_APP_PASSWORD:
    description: 'DEV_ID_APP_PASSWORD'
    required: true
  DEVELOPER_ID_APPLICATION:
    description: 'DEVELOPER_ID_APPLICATION'
    required: true
  DEV_ID_INSTALLER_CERT:
    description: 'DEV_ID_INSTALLER_CERT'
    required: true
  DEV_ID_INSTALLER_PASSWORD:
    description: 'DEV_ID_INSTALLER_PASSWORD'
    required: true
  DEVELOPER_ID_INSTALLER:
    description: 'DEVELOPER_ID_INSTALLER'
    required: true
  NOTARIZATION_USERNAME:
    description: 'NOTARIZATION_USERNAME'
    required: true
  NOTARIZATION_PASSWORD:
    description: 'NOTARIZATION_PASSWORD'
    required: true
  TEAM_ID:
    description: 'TEAM_ID'
    required: true
  PACKAGES_PROJECT:
    description: 'PACKAGES_PROJECT'
    required: true
  PACKAGE_NAME:
    description: 'PACKAGE_NAME'
    required: true
runs:
  using: "composite"
  steps:
    - name: Import Certificates
      uses: zones-convolution/basic-macos-keychain-action@main
      id: keychain
      with:
        dev-id-app-cert: ${{ inputs.DEV_ID_APP_CERT }}
        dev-id-app-password: ${{ inputs.DEV_ID_APP_PASSWORD }}
        dev-id-installer-cert: ${{ inputs.DEV_ID_INSTALLER_CERT }}
        dev-id-installer-password: ${{ inputs.DEV_ID_INSTALLER_PASSWORD }}

    - name: Codesign Plugin Binaries
      shell: bash
      run: |
        codesign --force -s "${{ inputs.DEVELOPER_ID_APPLICATION }}" -v "${{ env.VST3_PATH }}" --deep --strict --options=runtime --timestamp
        codesign --force -s "${{ inputs.DEVELOPER_ID_APPLICATION }}" -v "${{ env.AU_PATH }}" --deep --strict --options=runtime --timestamp

    - name: Install Packages
      shell: bash
      run: brew install --cask packages

    - name: Create installer
      shell: bash
      run: packagesbuild --project "${{ inputs.PACKAGES_PROJECT }}" --package-version "${{ env.VERSION }}"

    - name: Sign installer
      shell: bash
      run: |
        mkdir builds/signed
        productsign -s "${{ inputs.DEVELOPER_ID_INSTALLER }}" builds/Zones.pkg builds/signed/Zones.pkg

    - name: Notarize and Staple
      shell: bash
      run: |
        xcrun notarytool submit builds/signed/Zones.pkg --apple-id ${{ inputs.NOTARIZATION_USERNAME }} --password ${{ inputs.NOTARIZATION_PASSWORD }} --team-id ${{ inputs.TEAM_ID }} --wait
        xcrun stapler staple builds/signed/Zones.pkg

    - name: Upload PKG (macOS)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.PACKAGE_NAME }}
        path: builds/signed/Zones.pkg