name: "package_macos"
description: "Code-sign, apple notary service and package"
runs:
  using: "composite"
  steps:
    - name: Install Packages
      shell: bash
      run: brew install --cask packages
    - name: Create installer
      shell: bash
      run: packagesbuild --project ./zones.pkgproj VERSION="${{ env.VERSION }}"
    - name: Upload PKG (macOS)
      uses: actions/upload-artifact@v4
      with:
        name: Zones.pkg
        path: builds/Zones.pkg