# Thanks to https://github.com/sudara/pamplejuce for the inspiration behind this template.

name: build_and_test

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install JUCE's Linux Deps
        run: |
          sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev xvfb ninja-build
          # downgrade gcc to workaround 22.04 and C++20 issue 
          # see: https://github.com/actions/runner-images/issues/8659
          sudo apt-get install -y --allow-downgrades libc6=2.35-0ubuntu3.6 libc6-dev=2.35-0ubuntu3.6 libstdc++6=12.3.0-1ubuntu1~22.04 libgcc-s1=12.3.0-1ubuntu1~22.04
          sudo /usr/bin/Xvfb $DISPLAY &

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build and Test
        uses: ./.github/actions/build_and_test