# Thanks to Pamplejuce for getting this on the right track, https://github.com/sudara/pamplejuce/

name: build_and_release_arm

on:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  BUILD_TYPE: Release
  BUILD_DIR: builds/arm64-osx/client

jobs:
  build_and_package:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build ui
        uses: ./.github/actions/build_ui

      - name: Build and Test
        uses: ./.github/actions/build_and_test_arm

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Pluginval
        uses: ./.github/actions/pluginval
        with:
          VERSION: v1.0.3
          OS: macOS
          BINARY: pluginval.app/Contents/MacOS/pluginval
          VST3_PATH: ${{ env.VST3_PATH }}

      - name: Package MacOS
        uses: ./.github/actions/package_macos
        with:
          DEV_ID_APP_CERT: ${{ secrets.DEV_ID_APP_CERT }}
          DEV_ID_APP_PASSWORD: ${{ secrets.DEV_ID_APP_PASSWORD }}
          DEVELOPER_ID_APPLICATION: ${{ secrets.DEVELOPER_ID_APPLICATION }}
          DEV_ID_INSTALLER_CERT: ${{ secrets.DEV_ID_INSTALLER_CERT }}
          DEV_ID_INSTALLER_PASSWORD: ${{ secrets.DEV_ID_INSTALLER_PASSWORD }}
          DEVELOPER_ID_INSTALLER: ${{ secrets.DEVELOPER_ID_INSTALLER }}
          NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
          NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          PACKAGES_PROJECT: ./zones_arm64.pkgproj
          PACKAGE_NAME: Zones-arm64.pkg

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build_and_package
    permissions:
      contents: write

    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            */*.pkg