# Thanks to https://github.com/sudara/pamplejuce for the inspiration behind this template.

name: build_and_test

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  BUILD_TYPE: Release
  BUILD_DIR: builds/ninja-multi-vcpkg/client

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install JUCE's Linux Deps
        run: |
          sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.1-dev libglu1-mesa-dev libcurl4-openssl-dev xvfb ninja-build
          sudo /usr/bin/Xvfb $DISPLAY &

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build ui
        uses: ./.github/actions/build_ui

      - name: Build and Test
        uses: ./.github/actions/build_and_test