name: zones_tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: lukka/get-cmake@latest
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup vcpkg (it does not install any package yet)
        uses: lukka/run-vcpkg@v11